### ISSUE TITLE
Question about the FID

### ISSUE THREAD

**Issue by Junyang-gdut** [OFA-Sys/DAFlow#1]
![image](https://user-images.githubusercontent.com/68991221/180586375-78b461df-dcf1-4916-9c08-58106e34d96b.png)

Hi! This work presents a nice Garment Warping Job！ However，when I test the fid on VITON under unpaired setting as CP-VTON+, I get the result 10.53, which is different from the result in your paper.

All my steps are in accordance with Readme.md, can you tell me where is the problem with my setting?

thx.

**Comment by ShuaiBai623** [comment]
Thanks for your question, the model we provided corresponds to SDAFN (FID: 12.05 in paper) in Table2, which gets higher scores than reported in paper. SDAFN+ applies the prediction of SDAFN to replace the masked person and pose keypoints as the input for training, like PFAPN.

**Comment by Junyang-gdut** [comment]
ok，i get it。 Thx
