### ISSUE TITLE
How to get the human parsing result?

### ISSUE THREAD

**Issue by gjn2659338105** [OFA-Sys/DAFlow#18]
Before img_agnostic, how can I get the image under `image-parse-new`? Which human parse model should I use ?

**Comment by YELLOWHANDSOME1024** [comment]
> Before img_agnostic, how can I get the image under `image-parse-new`? Which human parse model should I use ?

 the original data is from CPVTON-plus

**Comment by MosbehBarhoumiRAI** [comment]
@gjn2659338105  According to the paper, the authors cited the approach used in their research from the following source: "https://arxiv.org/pdf/2207.09161v1.pdf". Additionally, the code implementation can be found at this GitHub repository: "https://github.com/Engineering-Course/LIP_SSL".

**Comment by gjn2659338105** [comment]
It helps me a lot.Thank you!
