### ISSUE TITLE
RuntimeError: DataLoader worker (pid(s) 3986) exited unexpectedly

### ISSUE THREAD

**Issue by maizer2** [OFA-Sys/DAFlow#4]
python -u test_SDAFNet_viton.py -b 8 --name TEST_PAIR --mode test --dataset_list VITON/test_pairs.txt --workers 0

**Comment by ShuaiBai623** [comment]
try add   ”drop_last=True“ in line 45, "test_loader = data.DataLoader(test_dataset, batch_size=opt.batch_size, shuffle=opt.shuffle,num_workers=opt.workers)"
