### ISSUE TITLE
How to make agnostic input for custom images

### ISSUE THREAD

**Issue by minar09** [OFA-Sys/DAFlow#5]
Hi, thank you very much for your nice repository and for providing the relevant models and data. Can you please share how did you make the agnostic image inputs so that I can test this model on custom images? Thank you.

**Comment by arunsubk** [comment]
Hi Minar, Repo-head,
Thanks for this great repo (to the repo-head). Any luck with the agnostic image creation? I intuitively think it is a human parser getting the mask and hand labels and masking it out with black, however, an easier opensource reference could really help. 
Thanks,
Arun

**Comment by minar09** [comment]
Hi @arunsubk , I found a nice function here: https://github.com/NadaAdelMousa/Virtual-Try-on/blob/f8f5ff1adbc44b681563b208ec9510e4182368b7/datasets.py#L68

**Comment by ShuaiBai623** [comment]
Thanks for your concern, the data process scripts are updated in `https://github.com/OFA-Sys/DAFlow/tree/main/data/data_process`.

**Comment by arunsubk** [comment]
Thanks a lot @ShuaiBai623 for the data process scripts, and thanks again for the great work. Could you please also let me know if there are pre-processing code for MPV dataset, you mentioned in the paper?
Regards,
Arun

**Comment by ShuaiBai623** [comment]
The pre-processing script for MPV is the same as VITION.
