### ISSUE TITLE
agnostic images generation

### ISSUE THREAD

**Issue by lizhi-ntu** [OFA-Sys/DAFlow#6]
Thank you for sharing the excellent work! Is there any algorithm to generate the agnostic images or the images are cropped manually?

**Comment by ShuaiBai623** [comment]
Thanks for your concern, the data process scripts are updated in `https://github.com/OFA-Sys/DAFlow/tree/main/data/data_process`.

**Comment by lizhi-ntu** [comment]
> Thanks for your concern, the data process scripts are updated in `https://github.com/OFA-Sys/DAFlow/tree/main/data/data_process`.

Got it with thanks.
