### ISSUE TITLE
Hello, what is your input for generating mask

### ISSUE THREAD

**Issue by zbq777sc** [OFA-Sys/DAFlow#7]
I want to run your code: data/data_process/get_img_agnostic.py

But I found that I didn't know what input it needed

Can you tell me, thank you!

**Comment by ShuaiBai623** [comment]
the input is the datapath and the filenames list. The datapath consists of the pose_keypoints, original clothes images, model images and human-parsing results, which are from  [CPVTON-plus](https://github.com/minar09/cp-vton-plus/).  Unzip the `viton_plus.zip` from CPVTON-plus.

**Comment by tengolagan** [comment]
Hi, please can you tell me how you get the human-parsing results (json files?) ? thanks!!

**Comment by tudragon154203** [comment]
> the input is the datapath and the filenames list. The datapath consists of the pose_keypoints, original clothes images, model images and human-parsing results, which are from [CPVTON-plus](https://github.com/minar09/cp-vton-plus/). Unzip the `viton_plus.zip` from CPVTON-plus.

I think the paper is about running a virtual trying without relying on extra stages like human-parsing. So we do still need the parsing in order to generate img agnostic, don't we?
